spring:
  h2:
    console:
      enabled: true
      path: /place

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./place
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    org:
      hibernate:
        sql: debug
        type: trace

kakao-open-api:
  place-search-keyword:
    url: https://dapi.kakao.com/v2/local/search/keyword.json
    app-key: 20d860c465148014adda59453ca9adba
  place-detail:
    url: https://map.kakao.com/link/map/{id}
